services:
  db:
    image: docker.io/postgres:17-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB:-dev}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-dev}"
      POSTGRES_USER: "${POSTGRES_USER:-dev}"

  pgweb:
    image: docker.io/sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER:-dev}:${POSTGRES_PASSWORD:-dev}@${POSTGRES_HOST:-db}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-dev}?sslmode=disable"
    entrypoint: /bin/bash
    command: [
      "-c",
      "until pg_isready -h ${POSTGRES_HOST:-db} -d ${POSTGRES_DB:-dev}; do echo 'wait for db'; sleep 1; done && pgweb --bind=0.0.0.0"
    ]
    depends_on:
      - db

  pg-maintenance:
    build:
      context: ./
      dockerfile: Dockerfile
    image: pg-maintenance
    container_name: pg-maintenance
    environment:
      DB_DSN: "host=${POSTGRES_HOST:-db} port=${POSTGRES_PORT:-5432} sslmode=${POSTGRES_SSL_MODE:-disable} user=${POSTGRES_USER:-dev} password=${POSTGRES_PASSWORD:-dev} dbname=${POSTGRES_DB:-dev}"
    command: ["/pg_maintenance", "--table", "dev", "--days", "10", "--batch", "100", "--timeout", "0"]
    depends_on:
      - db
