name: Build and Push Multi-Platform Docker Image on Release

on:
  release:
    types:
      - published  # Trigger only when a release is published.

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write  # Required to push images to GHCR.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create Docker Buildx Builder
        run: |
          docker buildx create --use --name mybuilder
          docker buildx inspect --bootstrap

      - name: Build and Push Multi-Platform Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.event.release.tag_name }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: Logout from Docker Registry
        run: docker logout ghcr.io
